### ISSUE TITLE
feat: add hot-reload capabilities to pharaoh. 

### ISSUE THREAD

**Issue by codekeyz** [Pharaoh-Framework/pharaoh#52]
**Description**

My running code should automatically reload. No need to do any additional setup.

**Additional Context**

- We might be able to achieve that using this library https://pub.dev/packages/hotreloader
- Also we can reference how it's done by shelf https://pub.dev/packages/shelf_hotreload

**Comment by fiifibenjamin22** [comment]
ok i will start my contribution by adding a nodemon similar task manager for hot reload.

**Comment by codekeyz** [comment]
@rasheedmhd Do we have an update on this ticket? We might be moved to de-prioritize if it's being a pain to figure out.

**Comment by rasheedmhd** [comment]
I looking into it and will give you an update if I think we should de-prioritize for now.

**Comment by iamEtornam** [comment]
I tried that too. It didn't work. I re-implement [angel_hot](https://github.com/angel-dart-archive/hot) but there's an issue i need to fix

**Comment by rasheedmhd** [comment]
Alright, keep us in the loop

**Comment by codekeyz** [comment]
This is good progress. I was almost giving up on it for now 😥. But I've been doing some benchmarks against other competitors like Fastify, Express etc. I'll share results when I'm through.

**Comment by codekeyz** [comment]
@iamEtornam @rasheedmhd I saw this while reading Jaspr codebase today. This should be somewhat helpful.

https://github.com/schultek/jaspr/blob/3495cfd0693fed99a34ffec0f9f0b8ac9bbfb18e/packages/jaspr/lib/src/server/server_app.dart#L97-L124

**Comment by rasheedmhd** [comment]
> I tried that too. It didn't work. I re-implement [angel_hot](https://github.com/angel-dart-archive/hot) but there's an issue i need to fix

@iamEtornam any updates on this? I have been looking into how the dart vm hotreload works and how we could possibly write something from the ground up. Just wanted to know your progress on this

**Comment by codekeyz** [comment]
Okay guys @rasheedmhd @iamEtornam I'm closing this ticket. 

This task is out of scope of this package. I'll be raising it in `Yaroo`. The full blown framework that uses Pharaoh underneath. That way it'll be pretty straight-forward to implement hot-reloading
