### ISSUE TITLE
Add Contributing .md file

### ISSUE THREAD

**Issue by mihrab34** [Pharaoh-Framework/pharaoh#61]
**Description**
I noticed that the project is currently missing a CONTRIBUTING.md file, which can serve as a valuable resource for new contributors and help streamline the contribution process. I propose adding this file to provide clear guidelines on contributing to the project.

**Proposed Changes:**

 Create a CONTRIBUTING.md file in the project root and include sections such as:
- [ ] Introduction
- [ ] Code of Conduct
- [ ] How to Contribute
- [ ] Issue Reporting
- [ ] Pull Requests
- [ ] Coding Guidelines
- [ ] Testing
- [ ] Review Process
- [ ] Communication Channels

**Additional Information**
I can create a pull request for this change and can collaborate with others to ensure the content is comprehensive and accurate.

Please share your thoughts and suggestions on this proposal @codekeyz 

Thank you!

**Comment by codekeyz** [comment]
This will make a good contribution @mihrab34. Thanks for taking this up

**Comment by mihrab34** [comment]
Opened a draft PR. Should be ready for review before EOD @codekeyz
